# Generated by Django 2.1.5 on 2019-02-09 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_text', models.CharField(max_length=100)),
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Chatbot',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_text', models.CharField(max_length=100)),
                ('answer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='chatbot.Question')),
            ],
        ),
    ]
